local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, {})
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader>sw', builtin.grep_string, {desc ="[S]earch current [W]ord"})
vim.keymap.set('n', '<leader>sg', builtin.live_grep, {desc = "[S]earch by [G]rep"})
vim.keymap.set("n", "<leader>sh", builtin.help_tags, {desc = '[S]earch [H]elp'})
